function app() {
  const day = 86400000;
  const now = () => new Date();
  const isoDays = (days) => new Date(Date.now() + days * day).toISOString();
  const uid = () => `job-${Date.now()}-${Math.random().toString(16).slice(2)}`;
  const initialJobs = [
    { id: 'backend', title: 'Backend Engineer', department: 'Engineering', recruiter: 'Alex Morgan', hiringManager: 'Priya Shah', requisitionId: 'REQ-2026-0142', headcountApproved: true, budgetApproved: true, employerVerified: true, location: 'Kuala Lumpur, Malaysia', employmentType: 'Full-time', seniority: 'Mid level', salaryMin: 90000, salaryMax: 125000, currency: 'MYR', salaryVisible: true, responsibilities: 'Build resilient platform APIs, partner with product teams, and improve service reliability.', requirements: [{ name: 'Node.js', type: 'Technical', required: true, years: 3, justification: 'Core API stack' }, { name: 'SQL', type: 'Technical', required: true, years: 3, justification: 'Data services' }], status: 'Published', publishedAt: isoDays(-6), lastConfirmedAt: isoDays(-3), confirmationDueAt: isoDays(27), freshnessStatus: 'Active and Confirmed', score: 92, warnings: [], blockers: [], comments: [], confirmationHistory: [{ at: isoDays(-3), by: 'Priya Shah', action: 'Still Hiring' }] },
    { id: 'graduate', title: 'Graduate Data Analyst', department: 'Data & Analytics', recruiter: 'Alex Morgan', hiringManager: 'Priya Shah', requisitionId: 'REQ-2026-0143', headcountApproved: true, budgetApproved: true, employerVerified: true, location: 'Kuala Lumpur, Malaysia', employmentType: 'Full-time', seniority: 'Entry level', salaryMin: 42000, salaryMax: 54000, currency: 'MYR', salaryVisible: true, responsibilities: 'Prepare dashboards, analyse business performance, and communicate findings to operations teams.', requirements: [{ name: 'SQL', type: 'Technical', required: true, years: 7, justification: 'Needed for reporting' }, { name: 'Python', type: 'Technical', required: true, years: 5, justification: 'Automation' }], status: 'Needs Changes', score: 54, warnings: ['Entry-level role requests excessive experience.'], blockers: [], comments: [], confirmationHistory: [] },
    { id: 'designer', title: 'Product Designer', department: 'Product', recruiter: 'Jamie Lee', hiringManager: 'Michael Chen', requisitionId: 'REQ-2026-0144', headcountApproved: true, budgetApproved: true, employerVerified: true, location: 'Remote, Malaysia', employmentType: 'Full-time', seniority: 'Mid level', salaryMin: 85000, salaryMax: 115000, currency: 'MYR', salaryVisible: true, responsibilities: 'Lead product discovery, prototype concepts, and improve end-to-end customer experiences.', requirements: [{ name: 'Figma', type: 'Technical', required: true, years: 3, justification: 'Design workflow' }], status: 'Pending Approval', score: 87, warnings: [], blockers: [], comments: [{ by: 'Jamie Lee', text: 'Ready for manager review.', at: isoDays(-1) }], confirmationHistory: [] },
    { id: 'marketing', title: 'Marketing Intern', department: 'Marketing', recruiter: 'Alex Morgan', hiringManager: '', requisitionId: '', headcountApproved: false, budgetApproved: false, employerVerified: false, location: '', employmentType: '', seniority: 'Internship', salaryMin: 0, salaryMax: 0, currency: 'MYR', salaryVisible: false, responsibilities: 'Support campaigns and perform any task requested.', requirements: [{ name: 'Marketing', type: 'Technical', required: true, years: 5, justification: '' }], status: 'Draft', score: 22, warnings: ['The description is vague and needs clearer responsibilities.'], blockers: ['Hiring manager is missing.', 'Requisition ID is missing.', 'Headcount approval is required.', 'Budget approval is required.'], comments: [], confirmationHistory: [] },
    { id: 'security', title: 'Cybersecurity Specialist', department: 'Security', recruiter: 'Alex Morgan', hiringManager: 'Priya Shah', requisitionId: 'REQ-2026-0145', headcountApproved: true, budgetApproved: true, employerVerified: true, location: 'Singapore', employmentType: 'Full-time', seniority: 'Senior', salaryMin: 125000, salaryMax: 165000, currency: 'MYR', salaryVisible: true, responsibilities: 'Own security operations, investigate incidents, and strengthen cloud controls.', requirements: [{ name: 'Cloud security', type: 'Technical', required: true, years: 6, justification: 'Core scope' }], status: 'Approved', score: 89, warnings: [], blockers: [], comments: [], confirmationHistory: [] },
    { id: 'operations', title: 'Operations Executive', department: 'Operations', recruiter: 'Jamie Lee', hiringManager: 'Michael Chen', requisitionId: 'REQ-2026-0146', headcountApproved: true, budgetApproved: true, employerVerified: true, location: 'Kuala Lumpur, Malaysia', employmentType: 'Full-time', seniority: 'Mid level', salaryMin: 62000, salaryMax: 78000, currency: 'MYR', salaryVisible: true, responsibilities: 'Improve service workflows, coordinate cross-functional reporting, and resolve operational risks.', requirements: [{ name: 'Excel', type: 'Technical', required: true, years: 3, justification: 'Reporting' }], status: 'Confirmation Due', publishedAt: isoDays(-27), lastConfirmedAt: isoDays(-27), confirmationDueAt: isoDays(3), freshnessStatus: 'Confirmation Due', score: 90, warnings: [], blockers: [], comments: [], confirmationHistory: [] },
    { id: 'ai-product', title: 'AI Product Manager', department: 'Product', recruiter: 'Alex Morgan', hiringManager: 'Priya Shah', requisitionId: 'REQ-2026-0147', headcountApproved: true, budgetApproved: true, employerVerified: true, location: 'Remote, Malaysia', employmentType: 'Full-time', seniority: 'Senior', salaryMin: 130000, salaryMax: 175000, currency: 'MYR', salaryVisible: true, responsibilities: 'Own AI product strategy, research customer outcomes, and lead delivery across data and engineering.', requirements: [{ name: 'Product strategy', type: 'Technical', required: true, years: 6, justification: 'Leadership scope' }], status: 'Paused as Stale', publishedAt: isoDays(-34), lastConfirmedAt: isoDays(-34), confirmationDueAt: isoDays(-4), pausedAt: isoDays(-4), freshnessStatus: 'Paused as Stale', score: 91, warnings: [], blockers: [], comments: [], confirmationHistory: [] },
    { id: 'filled', title: 'Platform Engineer', department: 'Engineering', recruiter: 'Jamie Lee', hiringManager: 'Michael Chen', requisitionId: 'REQ-2026-0148', headcountApproved: true, budgetApproved: true, employerVerified: true, location: 'Kuala Lumpur, Malaysia', employmentType: 'Full-time', seniority: 'Mid level', salaryMin: 98000, salaryMax: 130000, currency: 'MYR', salaryVisible: true, responsibilities: 'Operate platform tooling and improve deployment reliability.', requirements: [], status: 'Position Filled', filledAt: isoDays(-2), score: 88, warnings: [], blockers: [], comments: [], confirmationHistory: [] },
    { id: 'rejected', title: 'Sales Director', department: 'Revenue', recruiter: 'Alex Morgan', hiringManager: 'Priya Shah', requisitionId: 'REQ-2026-0149', headcountApproved: true, budgetApproved: true, employerVerified: true, location: 'Kuala Lumpur, Malaysia', employmentType: 'Full-time', seniority: 'Director', salaryMin: 80000, salaryMax: 90000, currency: 'MYR', salaryVisible: true, responsibilities: 'Lead enterprise sales.', requirements: [], status: 'Rejected', score: 61, warnings: ['Proposed salary is materially below the demonstration market range.'], blockers: [], comments: [{ by: 'Priya Shah', text: 'Salary and scope need to be revised before this can proceed.', at: isoDays(-3) }], confirmationHistory: [] },
  ];
  const defaultDraft = () => ({ id: '', requisitionId: '', department: 'Engineering', vacancies: 1, recruiter: 'Alex Morgan', hiringManager: '', targetStartDate: '', headcountApproved: false, budgetApproved: false, businessJustification: '', intendedPublicationDate: '', confirmationFrequency: 30, title: '', location: 'Kuala Lumpur, Malaysia', workplace: 'Hybrid', employmentType: 'Full-time', seniority: 'Entry level', salaryMin: '', salaryMax: '', currency: 'MYR', salaryVisible: true, reportingLine: '', summary: '', responsibilities: '', requirements: [{ name: '', type: 'Technical', required: true, years: 0, justification: '' }], employerVerified: true, status: 'Draft', warnings: [], blockers: [], score: 0, comments: [], confirmationHistory: [] });
  const saved = (() => { try { return JSON.parse(localStorage.getItem('careeros-verify-state') || ''); } catch { return null; } })();
  const hasDemoAccess = sessionStorage.getItem('careeros_demo_access') === 'true';
  return {
    screen: hasDemoAccess ? 'employer' : 'home', workspacePage: saved?.workspacePage || 'overview', mobileMenuOpen: false, role: saved?.role || 'Recruiter', jobs: saved?.jobs || initialJobs, audit: saved?.audit || [], draft: saved?.draft || defaultDraft(), wizardStep: 1, activeJobId: null, candidatePreviewJobId: null, freshnessJobId: null, validationRan: false, managerAttests: false, toast: '', loginEmail: 'recruiter@careeros.demo', demoTimeDays: saved?.demoTimeDays || 0,
    init() { if (!this.audit.length) this.addAudit('Demo mode entered', null, '', '', 'Demo workspace seeded for Talentbank Demo.'); this.persist(); },
    persist() { localStorage.setItem('careeros-verify-state', JSON.stringify({ workspacePage: this.workspacePage, role: this.role, jobs: this.jobs, audit: this.audit, draft: this.draft, demoTimeDays: this.demoTimeDays })); },
    navigate(screen) { this.screen = screen; this.mobileMenuOpen = false; this.persist(); window.scrollTo({ top: 0, behavior: 'smooth' }); },
    enterWorkspace(page = 'overview', created = false) { sessionStorage.setItem('careeros_demo_access', 'true'); this.screen = 'employer'; this.role = 'Recruiter'; this.workspacePage = page; this.persist(); if (created) this.notify('Demo workspace created.'); window.scrollTo({ top: 0, behavior: 'smooth' }); },
    logOut() { sessionStorage.removeItem('careeros_demo_access'); this.screen = 'home'; this.workspacePage = 'overview'; this.loginEmail = 'recruiter@careeros.demo'; window.scrollTo({ top: 0, behavior: 'smooth' }); },
    setPage(page) { this.workspacePage = page; this.activeJobId = null; this.candidatePreviewJobId = null; this.freshnessJobId = null; this.persist(); },
    addAudit(action, job, from = '', to = '', comment = '') { this.audit.unshift({ id: uid(), at: now().toLocaleString(), user: this.role === 'Hiring Manager' ? 'Priya Shah' : this.role === 'HR Administrator' ? 'Morgan Patel' : 'Alex Morgan', role: this.role, action, job: job?.title || 'Workspace', from, to, comment }); this.persist(); },
    notify(message) { this.toast = message; setTimeout(() => { this.toast = ''; }, 2800); },
    counts() { const c = {}; ['Draft', 'Needs Changes', 'Pending Approval', 'Approved', 'Published', 'Confirmation Due', 'Paused as Stale'].forEach(s => c[s] = this.jobs.filter(j => j.status === s).length); return c; },
    actionJobs() { return this.jobs.filter(j => ['Needs Changes', 'Pending Approval', 'Approved', 'Confirmation Due', 'Paused as Stale'].includes(j.status)); },
    job(id) { return this.jobs.find(j => j.id === id); },
    statusClass(status) { return ({ 'Draft':'status-slate','Needs Changes':'status-amber','Pending Approval':'status-blue','Approved':'status-green','Published':'status-green','Confirmation Due':'status-amber','Paused as Stale':'status-red','Rejected':'status-red','Position Filled':'status-slate','Closed':'status-slate' })[status] || 'status-slate'; },
    scoreClass(score) { return score >= 80 ? 'text-emerald-400' : score >= 60 ? 'text-amber-300' : 'text-red-400'; },
    formatDate(value) { return value ? new Date(value).toLocaleDateString(undefined, { month: 'short', day: 'numeric', year: 'numeric' }) : 'Not yet published'; },
    daysAgo(value) { return value ? Math.max(0, Math.floor((Date.now() - new Date(value).getTime()) / day)) : null; },
    startJob(job = null) { this.draft = job ? JSON.parse(JSON.stringify(job)) : defaultDraft(); this.wizardStep = 1; this.validationRan = false; this.setPage('create'); },
    addRequirement() { this.draft.requirements.push({ name: '', type: 'Technical', required: true, years: 0, justification: '' }); },
    removeRequirement(i) { this.draft.requirements.splice(i, 1); },
    validate(job = this.draft) {
      const blockers = [], warnings = [], passed = [];
      if (!job.hiringManager) blockers.push('Hiring manager is missing.'); else passed.push('Hiring manager is assigned');
      if (!job.requisitionId) blockers.push('Requisition ID is missing.'); else passed.push('requisition ID is present');
      if (!job.headcountApproved) blockers.push('Headcount approval is required.'); else passed.push('headcount is approved');
      if (!job.budgetApproved) blockers.push('Budget approval is required.'); else passed.push('budget is approved');
      if (!job.employerVerified) warnings.push('Employer verification evidence is incomplete.'); else passed.push('Demo Verified Employer evidence is on file');
      if (!job.location) warnings.push('Location is missing.');
      if (!job.employmentType) warnings.push('Employment type is missing.');
      if (!job.responsibilities || job.responsibilities.length < 55) warnings.push('Responsibilities are short or vague.');
      if (Number(job.salaryMin) && Number(job.salaryMax) && Number(job.salaryMin) > Number(job.salaryMax)) blockers.push('Minimum salary cannot exceed maximum salary.');
      if (!job.salaryVisible) warnings.push('Salary is hidden from candidates.');
      const required = job.requirements.filter(r => r.required);
      if (required.length > 8) warnings.push('Too many skills are marked required.');
      if ((job.seniority === 'Entry level' || job.seniority === 'Internship') && required.some(r => Number(r.years) > 3)) warnings.push('Entry-level role requests excessive experience.');
      if (job.seniority === 'Internship' && required.some(r => Number(r.years) > 1)) warnings.push('Internship requires more experience than the demonstration benchmark.');
      if ((job.summary + job.responsibilities).toLowerCase().match(/pay.*fee|bank password|national id|passport number/)) blockers.push('Potential candidate-payment or sensitive-information request detected.');
      const duplicate = required.map(r => r.name.trim().toLowerCase()).filter(Boolean).some((v, i, a) => a.indexOf(v) !== i);
      if (duplicate) warnings.push('Duplicate requirements should be consolidated.');
      const score = Math.max(0, Math.min(100, 100 - blockers.length * 22 - warnings.length * 7 + (job.employerVerified ? 0 : -8)));
      job.blockers = blockers; job.warnings = warnings; job.passed = passed; job.score = score; this.validationRan = true;
      this.addAudit('Validation run', job, job.status, job.status, `${blockers.length} blocker(s), ${warnings.length} warning(s), score ${score}.`);
      this.persist(); return { blockers, warnings, passed, score };
    },
    saveDraft() { const old = this.jobs.find(j => j.id === this.draft.id); if (!this.draft.id) { this.draft.id = uid(); this.draft.status = 'Draft'; this.jobs.unshift(JSON.parse(JSON.stringify(this.draft))); this.addAudit('Job created', this.draft, '', 'Draft'); } else { Object.assign(old, JSON.parse(JSON.stringify(this.draft))); if (['Approved','Published','Confirmation Due','Paused as Stale'].includes(old.status)) { old.status = 'Draft'; this.addAudit('Material edit invalidated approval', old, 'Approved', 'Draft'); } else this.addAudit('Job edited', old, '', old.status); } this.persist(); this.notify('Draft saved.'); },
    submitForApproval() { const result = this.validate(this.draft); if (result.blockers.length || result.score < 60) return this.notify('Resolve critical blockers before submitting.'); this.saveDraft(); const j = this.job(this.draft.id); j.status = 'Pending Approval'; this.addAudit('Submitted for manager approval', j, 'Draft', 'Pending Approval'); this.persist(); this.notify('Submitted to the hiring manager.'); this.setPage('approvals'); },
    approve(job) { if (this.role !== 'Hiring Manager') return this.notify('Switch Demo Role to Hiring Manager to approve.'); if (!this.managerAttests) return this.notify('Manager attestation is required.'); if (job.recruiter === 'Priya Shah') return this.notify('Recruiters cannot approve their own submission.'); const from = job.status; job.status = 'Approved'; job.approvedAt = now().toISOString(); this.addAudit('Approved with attestation', job, from, 'Approved', 'Approved, funded, and intended to be filled.'); this.managerAttests = false; this.persist(); this.notify('Vacancy approved and ready to publish.'); },
    requestChanges(job) { if (this.role !== 'Hiring Manager') return this.notify('Switch Demo Role to Hiring Manager to request changes.'); const from = job.status; job.status = 'Needs Changes'; job.comments.push({ by: 'Priya Shah', at: now().toISOString(), text: 'Please clarify the requirements and resolve the validation findings.' }); this.addAudit('Changes requested', job, from, 'Needs Changes'); this.persist(); this.notify('Changes requested from recruiter.'); },
    reject(job) { if (this.role !== 'Hiring Manager') return this.notify('Switch Demo Role to Hiring Manager to reject.'); const from = job.status; job.status = 'Rejected'; this.addAudit('Rejected', job, from, 'Rejected', 'Rejected in demo review.'); this.persist(); },
    publish(job) { if (this.role !== 'Recruiter') return this.notify('Switch Demo Role to Recruiter to publish.'); if (job.status !== 'Approved') return this.notify('Only approved jobs can be published.'); job.status = 'Published'; job.publishedAt = now().toISOString(); job.lastConfirmedAt = now().toISOString(); job.confirmationDueAt = isoDays(30); job.freshnessStatus = 'Active and Confirmed'; job.confirmationHistory.push({ at: now().toISOString(), by: 'Alex Morgan', action: 'Published' }); this.addAudit('Verification published', job, 'Approved', 'Published'); this.persist(); this.notify('CareerOS Verified Vacancy is now available.'); },
    confirm(job) { if (this.role !== 'Hiring Manager' && this.role !== 'HR Administrator') return this.notify('Switch Demo Role to Hiring Manager or HR Administrator to confirm active hiring.'); if (!['Published','Confirmation Due','Paused as Stale'].includes(job.status)) return; const from = job.status; job.status = 'Published'; job.lastConfirmedAt = now().toISOString(); job.confirmationDueAt = isoDays(30); job.freshnessStatus = 'Active and Confirmed'; delete job.pausedAt; job.confirmationHistory.push({ at: now().toISOString(), by: this.role === 'HR Administrator' ? 'Morgan Patel' : 'Priya Shah', action: from === 'Paused as Stale' ? 'Reconfirm and Reactivate' : 'Still Hiring' }); this.addAudit(from === 'Paused as Stale' ? 'Vacancy restored' : 'Vacancy reconfirmed', job, from, 'Published'); this.persist(); this.notify('Active hiring confirmed for another 30 days.'); },
    setLifecycle(job, action) { if (this.role !== 'Hiring Manager' && this.role !== 'HR Administrator') return this.notify('Switch Demo Role to Hiring Manager or HR Administrator for lifecycle actions.'); const from = job.status; if (action === 'pause') { job.status = 'Paused as Stale'; job.pausedAt = now().toISOString(); job.freshnessStatus = 'Paused as Stale'; }
      if (action === 'filled') { job.status = 'Position Filled'; job.filledAt = now().toISOString(); job.freshnessStatus = 'Position Filled'; }
      if (action === 'close') { job.status = 'Closed'; job.closedAt = now().toISOString(); job.freshnessStatus = 'Closed'; }
      this.addAudit(action === 'pause' ? 'Vacancy paused' : action === 'filled' ? 'Position filled' : 'Job closed', job, from, job.status); this.freshnessJobId = null; this.persist(); },
    keepPaused() { this.freshnessJobId = null; this.notify('Vacancy remains paused and hidden from candidates.'); },
    advanceTime() { this.demoTimeDays += 7; this.jobs.forEach(j => { if (!j.publishedAt || !['Published','Confirmation Due'].includes(j.status)) return; const age = this.daysAgo(j.lastConfirmedAt) + this.demoTimeDays; const from = j.status; if (age >= 30) { j.status = 'Paused as Stale'; j.pausedAt = now().toISOString(); j.freshnessStatus = 'Paused as Stale'; this.addAudit('Vacancy automatically paused', j, from, 'Paused as Stale', 'No active-hiring confirmation within 30 days.'); } else if (age >= 25 && j.status === 'Published') { j.status = 'Confirmation Due'; j.freshnessStatus = 'Confirmation Due'; this.addAudit('Confirmation became due', j, 'Published', 'Confirmation Due'); } }); this.persist(); this.notify('Demo time advanced by 7 days.'); },
    trustedJobs() { return this.jobs.filter(j => ['Published','Confirmation Due'].includes(j.status) && j.freshnessStatus !== 'Paused as Stale'); },
    demandSkills() { const m = {}; this.trustedJobs().forEach(j => j.requirements.filter(r => r.required).forEach(r => { if (r.name) m[r.name] = (m[r.name] || 0) + 1; })); return Object.entries(m).sort((a,b) => b[1]-a[1]); },
    resetDemo() { localStorage.removeItem('careeros-verify-state'); location.reload(); },
  };
}
